---
    - name: Power On Instance
      gcp_compute_instance:
         state: present
         name: "{{ instance_id }}"
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         status: running
         scopes:
           - https://www.googleapis.com/auth/compute
      register: instance
