---
    - name: Power On Instance
      gcp_compute_instance:
         state: present
         name: "{{ instance_id }}"
         zone: "{{ zone }}"
         project: "{{ gce_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gce_credentials_file_path }}"
         scopes:
           - https://www.googleapis.com/auth/compute
      register: instance
