---
    - debug:
        msg: "{{ gcp_project }}"

    - name: Power On Instance
      gcp_compute_instance:
         state: present
         deletion_protection: no
         name: "{{ instance_id.stdout }}"
         zone: "{{ zone.stdout }}"
         project: "{{ gcp_project.stdout }}"
         auth_kind: "{{ gcp_cred_kind }}"
         status: RUNNING
         scopes:
           - https://www.googleapis.com/auth/compute
      register: instance
