---
    - debug:
        msg: "{{ gcp_project }}"

    - name: Power On Instance
      gcp_compute_instance:
         state: present
         deletion_protection: no
         name: "{{ instance_id }}"
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind |string }}"
         status: RUNNING
         scopes:
           - https://www.googleapis.com/auth/compute
      register: instance
